---
- name: install patch 
  apt:
    name: patch
    state: latest 
     
- name: copy cloud-init patch
  copy:
    src: cloud-init-trusty.patch
    dest: /tmp/cloud-init.patch

- name: patch cloud-init
  shell: |
    set -uexo pipefail
    pushd /usr/lib/python2.7/dist-packages/cloudinit/distros/
    patch -p 1 <  /tmp/cloud-init.patch
    popd
    # Create .pyc files
    rm /usr/lib/python2.7/dist-packages/cloudinit/distros/__init__.pyc \
       /usr/lib/python2.7/dist-packages/cloudinit/distros/debian.pyc \
       /usr/lib/python2.7/dist-packages/cloudinit/distros/rhel.pyc \
       /usr/lib/python2.7/dist-packages/cloudinit/distros/sles.pyc
    python -c "import cloudinit.distros.debian; import cloudinit.distros.rhel; import cloudinit.distros.sles"
    rm /tmp/cloud-init.patch
  args:
    executable: /bin/bash
