- name: install scipion3 dependencies
  apt:
    name: [gcc, g++, make, libopenmpi-dev, python3-tk, libfftw3-dev, libhdf5-dev, libtiff-dev, libjpeg-dev, libsqlite3-dev, openjdk-8-jdk]
    state: latest
  debug:
    msg: "After installing dependencies"
- name: add group "scipion"
  group: name=scipion

- name: add user "scipion"
  user: name=scipion group=scipion home=/home/scipion createhome=yes

- name: Create the scipion3 directory
  file: path=/opt/scipion3 owner=scipion group=scipion state=directory

- name: Install scipion3 installer
  become: yes
  become_user: scipion
  shell:
    cmd: python -m pip install --user scipion-installer

- name: Install scipion3
  become: yes
  become_user: scipion
    shell:
      cmd: python -m scipioninstaller /path/where/you/want/scipion -venv -j 4
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/cuda/bin"