- hosts: all
  become: true
  tasks:
  - name: Add cuda GPG key
    apt_key:
      url: "http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub"
      state: present
  - name: Install NVIDIA CUDA 10.1 network deb repo from the network
    apt:
      deb: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.1.243-1_amd64.deb
  - name: Install the rest of CUDA based on network deb's config
    apt:
      update_cache: yes
      name: cuda-10-1

  - name: Blacklist nouveau driver
    copy:
      content:
        "blacklist nouveau"
      dest: /etc/modprobe.d/nouveau.conf

  - name: install virtualgl package
    apt:
      deb: https://sourceforge.net/projects/virtualgl/files/2.6.4/virtualgl_2.6.4_amd64.deb

  - name: Configure vglserver
    command: /opt/VirtualGL/bin/vglserver_config -config

  - name: Add user scipion to vlgusers group
    user:
      name: scipion
      state: present
      groups: vglusers
      append: yes

  - name: create Desktop folder for user scipion
    file:
      path: /home/scipion/Desktop
      state: directory
      mode: 0755

  - name: create scipion desktop shortcut
    copy:
      content:
        "[Desktop Entry]\n
        Version=1.0\n
        Type=Application\n
        Name=Scipion\n
        Comment=Scipion run with vglrun
        Exec=/opt/VirtualGL/bin/vglrun /home/scipion/scipion3/scipion3\n
        Icon=/home/scipion/scipion3/.scipion3env/lib/python3.6/site-packages/pyworkflow/resources/scipion_logo.gif\n
        Terminal=true\n
        StartupNotify=false\n"
      dest: /home/scipion/Desktop/scipion.desktop
      owner: scipion
      group: scipion