- hosts: all
  become: true
  gather_facts: False
  tasks:
  - name: install python
    raw: test -e /usr/bin/python || (apt-get update && apt-get install -y python-minimal || apt-get install python3-minimal)

  - name: update packages
    apt: upgrade=dist

  - name: add group "scipion"
    group: name=scipion

  - name: add user "scipion"
    user: name=scipion group=scipion home=/home/scipion createhome=yes shell=/bin/bash