- hosts: all
  become: true
  tasks:
  - name: get mesa software
    unarchive:
      src: http://scipion.cnb.csic.es/downloads/packages/mesa-11.0.7-compiled.tgz
      dest: /home/scipion/scipion3/software/em/
      remote_src: True

  - name: add mesa lib to LD_LIBRARY_PATH
    lineinfile:
      path: /home/scipion/.bashrc
      line: 'export LD_LIBRARY_PATH=/home/scipion/scipion3/software/em/mesa-11.0.7/lib:$LD_LIBRARY_PATH'

  - name: create Desktop folder for user scipion
    file:
      path: /home/scipion/Desktop
      state: directory
      mode: 0755
    owner: scipion
    group: scipion

  - name: create scipion desktop shortcut
    copy:
      content:
        "[Desktop Entry]\n
        Version=1.0\n
        Type=Application\n
        Name=Scipion\n
        Comment=Scipion run\n
        Exec=/home/scipion/scipion3/scipion3\n
        Icon=/home/scipion/scipion3/.scipion3env/lib/python3.6/site-packages/pyworkflow/resources/scipion_logo.gif\n
        Terminal=true\n
        StartupNotify=false\n"
      dest: /home/scipion/Desktop/scipion.desktop
      owner: scipion
      group: scipion
